package bbs.chat.mybatis.entity;

import java.util.ArrayList;
import java.util.List;
import bbs.chat.enuma.ChatType;

public class TChatExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public TChatExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> chatTypeCriteria;
		protected List<Criterion> allCriteria;
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
			chatTypeCriteria = new ArrayList<Criterion>();
		}

		public List<Criterion> getChatTypeCriteria() {
			return chatTypeCriteria;
		}

		protected void addChatTypeCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			chatTypeCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumOrdinalTypeHandler"));
			allCriteria = null;
		}

		protected void addChatTypeCriterion(String condition, ChatType value1, ChatType value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			chatTypeCriteria
					.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumOrdinalTypeHandler"));
			allCriteria = null;
		}

		public boolean isValid() {
			return criteria.size() > 0 || chatTypeCriteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			if (allCriteria == null) {
				allCriteria = new ArrayList<Criterion>();
				allCriteria.addAll(criteria);
				allCriteria.addAll(chatTypeCriteria);
			}
			return allCriteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
			allCriteria = null;
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
			allCriteria = null;
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
			allCriteria = null;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andChatTypeIsNull() {
			addCriterion("chat_type is null");
			return (Criteria) this;
		}

		public Criteria andChatTypeIsNotNull() {
			addCriterion("chat_type is not null");
			return (Criteria) this;
		}

		public Criteria andChatTypeEqualTo(ChatType value) {
			addChatTypeCriterion("chat_type =", value, "chatType");
			return (Criteria) this;
		}

		public Criteria andChatTypeNotEqualTo(ChatType value) {
			addChatTypeCriterion("chat_type <>", value, "chatType");
			return (Criteria) this;
		}

		public Criteria andChatTypeGreaterThan(ChatType value) {
			addChatTypeCriterion("chat_type >", value, "chatType");
			return (Criteria) this;
		}

		public Criteria andChatTypeGreaterThanOrEqualTo(ChatType value) {
			addChatTypeCriterion("chat_type >=", value, "chatType");
			return (Criteria) this;
		}

		public Criteria andChatTypeLessThan(ChatType value) {
			addChatTypeCriterion("chat_type <", value, "chatType");
			return (Criteria) this;
		}

		public Criteria andChatTypeLessThanOrEqualTo(ChatType value) {
			addChatTypeCriterion("chat_type <=", value, "chatType");
			return (Criteria) this;
		}

		public Criteria andChatTypeIn(List<ChatType> values) {
			addChatTypeCriterion("chat_type in", values, "chatType");
			return (Criteria) this;
		}

		public Criteria andChatTypeNotIn(List<ChatType> values) {
			addChatTypeCriterion("chat_type not in", values, "chatType");
			return (Criteria) this;
		}

		public Criteria andChatTypeBetween(ChatType value1, ChatType value2) {
			addChatTypeCriterion("chat_type between", value1, value2, "chatType");
			return (Criteria) this;
		}

		public Criteria andChatTypeNotBetween(ChatType value1, ChatType value2) {
			addChatTypeCriterion("chat_type not between", value1, value2, "chatType");
			return (Criteria) this;
		}

		public Criteria andSenderIdIsNull() {
			addCriterion("sender_id is null");
			return (Criteria) this;
		}

		public Criteria andSenderIdIsNotNull() {
			addCriterion("sender_id is not null");
			return (Criteria) this;
		}

		public Criteria andSenderIdEqualTo(Long value) {
			addCriterion("sender_id =", value, "senderId");
			return (Criteria) this;
		}

		public Criteria andSenderIdNotEqualTo(Long value) {
			addCriterion("sender_id <>", value, "senderId");
			return (Criteria) this;
		}

		public Criteria andSenderIdGreaterThan(Long value) {
			addCriterion("sender_id >", value, "senderId");
			return (Criteria) this;
		}

		public Criteria andSenderIdGreaterThanOrEqualTo(Long value) {
			addCriterion("sender_id >=", value, "senderId");
			return (Criteria) this;
		}

		public Criteria andSenderIdLessThan(Long value) {
			addCriterion("sender_id <", value, "senderId");
			return (Criteria) this;
		}

		public Criteria andSenderIdLessThanOrEqualTo(Long value) {
			addCriterion("sender_id <=", value, "senderId");
			return (Criteria) this;
		}

		public Criteria andSenderIdIn(List<Long> values) {
			addCriterion("sender_id in", values, "senderId");
			return (Criteria) this;
		}

		public Criteria andSenderIdNotIn(List<Long> values) {
			addCriterion("sender_id not in", values, "senderId");
			return (Criteria) this;
		}

		public Criteria andSenderIdBetween(Long value1, Long value2) {
			addCriterion("sender_id between", value1, value2, "senderId");
			return (Criteria) this;
		}

		public Criteria andSenderIdNotBetween(Long value1, Long value2) {
			addCriterion("sender_id not between", value1, value2, "senderId");
			return (Criteria) this;
		}

		public Criteria andGroupNameIsNull() {
			addCriterion("group_name is null");
			return (Criteria) this;
		}

		public Criteria andGroupNameIsNotNull() {
			addCriterion("group_name is not null");
			return (Criteria) this;
		}

		public Criteria andGroupNameEqualTo(String value) {
			addCriterion("group_name =", value, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameNotEqualTo(String value) {
			addCriterion("group_name <>", value, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameGreaterThan(String value) {
			addCriterion("group_name >", value, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameGreaterThanOrEqualTo(String value) {
			addCriterion("group_name >=", value, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameLessThan(String value) {
			addCriterion("group_name <", value, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameLessThanOrEqualTo(String value) {
			addCriterion("group_name <=", value, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameLike(String value) {
			addCriterion("group_name like", value, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameNotLike(String value) {
			addCriterion("group_name not like", value, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameIn(List<String> values) {
			addCriterion("group_name in", values, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameNotIn(List<String> values) {
			addCriterion("group_name not in", values, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameBetween(String value1, String value2) {
			addCriterion("group_name between", value1, value2, "groupName");
			return (Criteria) this;
		}

		public Criteria andGroupNameNotBetween(String value1, String value2) {
			addCriterion("group_name not between", value1, value2, "groupName");
			return (Criteria) this;
		}

		public Criteria andRecipientIdIsNull() {
			addCriterion("recipient_id is null");
			return (Criteria) this;
		}

		public Criteria andRecipientIdIsNotNull() {
			addCriterion("recipient_id is not null");
			return (Criteria) this;
		}

		public Criteria andRecipientIdEqualTo(Long value) {
			addCriterion("recipient_id =", value, "recipientId");
			return (Criteria) this;
		}

		public Criteria andRecipientIdNotEqualTo(Long value) {
			addCriterion("recipient_id <>", value, "recipientId");
			return (Criteria) this;
		}

		public Criteria andRecipientIdGreaterThan(Long value) {
			addCriterion("recipient_id >", value, "recipientId");
			return (Criteria) this;
		}

		public Criteria andRecipientIdGreaterThanOrEqualTo(Long value) {
			addCriterion("recipient_id >=", value, "recipientId");
			return (Criteria) this;
		}

		public Criteria andRecipientIdLessThan(Long value) {
			addCriterion("recipient_id <", value, "recipientId");
			return (Criteria) this;
		}

		public Criteria andRecipientIdLessThanOrEqualTo(Long value) {
			addCriterion("recipient_id <=", value, "recipientId");
			return (Criteria) this;
		}

		public Criteria andRecipientIdIn(List<Long> values) {
			addCriterion("recipient_id in", values, "recipientId");
			return (Criteria) this;
		}

		public Criteria andRecipientIdNotIn(List<Long> values) {
			addCriterion("recipient_id not in", values, "recipientId");
			return (Criteria) this;
		}

		public Criteria andRecipientIdBetween(Long value1, Long value2) {
			addCriterion("recipient_id between", value1, value2, "recipientId");
			return (Criteria) this;
		}

		public Criteria andRecipientIdNotBetween(Long value1, Long value2) {
			addCriterion("recipient_id not between", value1, value2, "recipientId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_chat
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_chat
     *
     * @mbg.generated do_not_delete_during_merge Sat Aug 11 13:33:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}