package bbs.chat.mybatis.entity;

import bbs.chat.enuma.ChatType;

public class TChat {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_chat.id
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_chat.chat_type
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	private ChatType chatType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_chat.sender_id
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	private Long senderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_chat.group_name
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	private String groupName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_chat.recipient_id
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	private Long recipientId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_chat.id
	 * @return  the value of t_chat.id
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_chat.id
	 * @param id  the value for t_chat.id
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_chat.chat_type
	 * @return  the value of t_chat.chat_type
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public ChatType getChatType() {
		return chatType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_chat.chat_type
	 * @param chatType  the value for t_chat.chat_type
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public void setChatType(ChatType chatType) {
		this.chatType = chatType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_chat.sender_id
	 * @return  the value of t_chat.sender_id
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public Long getSenderId() {
		return senderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_chat.sender_id
	 * @param senderId  the value for t_chat.sender_id
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public void setSenderId(Long senderId) {
		this.senderId = senderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_chat.group_name
	 * @return  the value of t_chat.group_name
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_chat.group_name
	 * @param groupName  the value for t_chat.group_name
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_chat.recipient_id
	 * @return  the value of t_chat.recipient_id
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public Long getRecipientId() {
		return recipientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_chat.recipient_id
	 * @param recipientId  the value for t_chat.recipient_id
	 * @mbg.generated  Sat Aug 11 13:39:01 CST 2018
	 */
	public void setRecipientId(Long recipientId) {
		this.recipientId = recipientId;
	}
}