package bbs.chat.mybatis.entity;

import java.util.Date;

public class TMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.id
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.content
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.pub_time
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    private Date pubTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.sender_id
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    private Long senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.chat_id
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    private Long chatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.is_readed
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    private Byte isReaded;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.id
     *
     * @return the value of t_message.id
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.id
     *
     * @param id the value for t_message.id
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.content
     *
     * @return the value of t_message.content
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.content
     *
     * @param content the value for t_message.content
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.pub_time
     *
     * @return the value of t_message.pub_time
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public Date getPubTime() {
        return pubTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.pub_time
     *
     * @param pubTime the value for t_message.pub_time
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public void setPubTime(Date pubTime) {
        this.pubTime = pubTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.sender_id
     *
     * @return the value of t_message.sender_id
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public Long getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.sender_id
     *
     * @param senderId the value for t_message.sender_id
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.chat_id
     *
     * @return the value of t_message.chat_id
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public Long getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.chat_id
     *
     * @param chatId the value for t_message.chat_id
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public void setChatId(Long chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.is_readed
     *
     * @return the value of t_message.is_readed
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public Byte getIsReaded() {
        return isReaded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.is_readed
     *
     * @param isReaded the value for t_message.is_readed
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    public void setIsReaded(Byte isReaded) {
        this.isReaded = isReaded;
    }
}