package bbs.usercenter.mybatis.mapper;

import bbs.usercenter.mybatis.entity.TUserProfile;
import bbs.usercenter.mybatis.entity.TUserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserProfileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	long countByExample(TUserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	int deleteByExample(TUserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	int insert(TUserProfile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	int insertSelective(TUserProfile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	List<TUserProfile> selectByExample(TUserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	TUserProfile selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TUserProfile record, @Param("example") TUserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	int updateByExample(@Param("record") TUserProfile record, @Param("example") TUserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	int updateByPrimaryKeySelective(TUserProfile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_profile
	 * @mbg.generated  Sat Jul 21 11:56:32 CST 2018
	 */
	int updateByPrimaryKey(TUserProfile record);
}