package bbs.forum.entity;

public class TForum {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_forum.id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_forum.forum_name
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	private String forumName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_forum.id
	 * @return  the value of t_forum.id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_forum.id
	 * @param id  the value for t_forum.id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_forum.forum_name
	 * @return  the value of t_forum.forum_name
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public String getForumName() {
		return forumName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_forum.forum_name
	 * @param forumName  the value for t_forum.forum_name
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public void setForumName(String forumName) {
		this.forumName = forumName;
	}
}