package bbs.forum.entity;

import java.util.Date;

public class TPost {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.content
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.author_id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	private Long authorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.pub_time
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	private Date pubTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.last_modified_time
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	private Date lastModifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.reply_post_id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	private Long replyPostId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.topic_id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	private Long topicId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.id
	 * @return  the value of t_post.id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.id
	 * @param id  the value for t_post.id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.content
	 * @return  the value of t_post.content
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.content
	 * @param content  the value for t_post.content
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.author_id
	 * @return  the value of t_post.author_id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public Long getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.author_id
	 * @param authorId  the value for t_post.author_id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public void setAuthorId(Long authorId) {
		this.authorId = authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.pub_time
	 * @return  the value of t_post.pub_time
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public Date getPubTime() {
		return pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.pub_time
	 * @param pubTime  the value for t_post.pub_time
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.last_modified_time
	 * @return  the value of t_post.last_modified_time
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public Date getLastModifiedTime() {
		return lastModifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.last_modified_time
	 * @param lastModifiedTime  the value for t_post.last_modified_time
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.reply_post_id
	 * @return  the value of t_post.reply_post_id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public Long getReplyPostId() {
		return replyPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.reply_post_id
	 * @param replyPostId  the value for t_post.reply_post_id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public void setReplyPostId(Long replyPostId) {
		this.replyPostId = replyPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.topic_id
	 * @return  the value of t_post.topic_id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public Long getTopicId() {
		return topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.topic_id
	 * @param topicId  the value for t_post.topic_id
	 * @mbg.generated  Tue Jul 10 12:44:08 CST 2018
	 */
	public void setTopicId(Long topicId) {
		this.topicId = topicId;
	}

	public TPost() {
		super();
		// TODO Auto-generated constructor stub
	}

	public TPost(String content, Long authorId, Long replyPostId, Long topicId) {
		super();
		this.content = content;
		this.authorId = authorId;
		this.replyPostId = replyPostId;
		this.topicId = topicId;
	}
}