package bbs.forum.entity;

import java.util.Date;

public class TTopic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic.id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic.author_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	private Long authorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic.forum_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	private Integer forumId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic.title
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic.pub_time
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	private Date pubTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic.views
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	private Integer views;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic.replies
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	private Integer replies;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic.likes
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	private Integer likes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic.main_post_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	private Long mainPostId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic.last_reply_post_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	private Long lastReplyPostId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic.id
	 * @return  the value of t_topic.id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic.id
	 * @param id  the value for t_topic.id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic.author_id
	 * @return  the value of t_topic.author_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public Long getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic.author_id
	 * @param authorId  the value for t_topic.author_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public void setAuthorId(Long authorId) {
		this.authorId = authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic.forum_id
	 * @return  the value of t_topic.forum_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public Integer getForumId() {
		return forumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic.forum_id
	 * @param forumId  the value for t_topic.forum_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public void setForumId(Integer forumId) {
		this.forumId = forumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic.title
	 * @return  the value of t_topic.title
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic.title
	 * @param title  the value for t_topic.title
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic.pub_time
	 * @return  the value of t_topic.pub_time
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public Date getPubTime() {
		return pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic.pub_time
	 * @param pubTime  the value for t_topic.pub_time
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic.views
	 * @return  the value of t_topic.views
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public Integer getViews() {
		return views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic.views
	 * @param views  the value for t_topic.views
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public void setViews(Integer views) {
		this.views = views;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic.replies
	 * @return  the value of t_topic.replies
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public Integer getReplies() {
		return replies;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic.replies
	 * @param replies  the value for t_topic.replies
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public void setReplies(Integer replies) {
		this.replies = replies;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic.likes
	 * @return  the value of t_topic.likes
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public Integer getLikes() {
		return likes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic.likes
	 * @param likes  the value for t_topic.likes
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public void setLikes(Integer likes) {
		this.likes = likes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic.main_post_id
	 * @return  the value of t_topic.main_post_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public Long getMainPostId() {
		return mainPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic.main_post_id
	 * @param mainPostId  the value for t_topic.main_post_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public void setMainPostId(Long mainPostId) {
		this.mainPostId = mainPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic.last_reply_post_id
	 * @return  the value of t_topic.last_reply_post_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public Long getLastReplyPostId() {
		return lastReplyPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic.last_reply_post_id
	 * @param lastReplyPostId  the value for t_topic.last_reply_post_id
	 * @mbg.generated  Thu Jul 12 17:13:32 CST 2018
	 */
	public void setLastReplyPostId(Long lastReplyPostId) {
		this.lastReplyPostId = lastReplyPostId;
	}
}