package bbs.chat.mybatis.mapper;

import bbs.chat.mybatis.entity.TMessage;
import bbs.chat.mybatis.entity.TMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    long countByExample(TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    int deleteByExample(TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    int insert(TMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    int insertSelective(TMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    List<TMessage> selectByExample(TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    TMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMessage record, @Param("example") TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    int updateByExample(@Param("record") TMessage record, @Param("example") TMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    int updateByPrimaryKeySelective(TMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Sat Aug 11 13:39:01 CST 2018
     */
    int updateByPrimaryKey(TMessage record);

	void readMessage(long messageId);
}