package bbs.forum.mapper;

import bbs.forum.DTO.Forum;
import bbs.forum.entity.TForum;
import bbs.forum.entity.TForumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TForumMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	long countByExample(TForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int deleteByExample(TForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int insert(TForum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int insertSelective(TForum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	List<TForum> selectByExample(TForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	TForum selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TForum record, @Param("example") TForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int updateByExample(@Param("record") TForum record, @Param("example") TForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int updateByPrimaryKeySelective(TForum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int updateByPrimaryKey(TForum record);

	List<TForum> selectAll();

	Forum selectForumById(int forumId);

	List<Forum> selectAllForum();
}