package bbs.forum.mapper;

import bbs.forum.entity.TManager;
import bbs.forum.entity.TManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TManagerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	long countByExample(TManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int deleteByExample(TManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int insert(TManager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int insertSelective(TManager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	List<TManager> selectByExample(TManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	TManager selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TManager record, @Param("example") TManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int updateByExample(@Param("record") TManager record, @Param("example") TManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int updateByPrimaryKeySelective(TManager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_manager
	 * @mbg.generated  Wed Jul 18 20:48:30 CST 2018
	 */
	int updateByPrimaryKey(TManager record);
}