package bbs.forum.mapper;

import bbs.form.utils.PageParam;
import bbs.forum.DTO.Topic;
import bbs.forum.entity.TTopic;
import bbs.forum.entity.TTopicExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTopicMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	long countByExample(TTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	int deleteByExample(TTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	int insert(TTopic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	int insertSelective(TTopic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	List<TTopic> selectByExample(TTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	TTopic selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TTopic record, @Param("example") TTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	int updateByExample(@Param("record") TTopic record, @Param("example") TTopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	int updateByPrimaryKeySelective(TTopic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri Aug 10 00:34:01 CST 2018
	 */
	int updateByPrimaryKey(TTopic record);

	Topic selectTopicById(Long topicId);

	void likesPlusOne(@Param("topicId") long topicId);
	
	void viewsPlusOne(@Param("topicId") long topicId);
	
	void repliesPlusOne(@Param("topicId") long topicId);

	List<Topic> selectAllTopicByForumId(@Param("forumId") long forumId,@Param("pageParam") PageParam pageParam);

	List<Topic> searchAllTopic(@Param("title")String title,@Param("pageParam") PageParam pageParam);

	List<Topic> selectAllTopicByUid(@Param("authorId")Long authorId, @Param("pageParam")PageParam pageParam);

	int countByUidAndTopicId(@Param("userId") Long uid,@Param("topicId") long topicId);
}