package bbs.forum.mapper;

import bbs.forum.entity.TUserPrincipalForum;
import bbs.forum.entity.TUserPrincipalForumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserPrincipalForumMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	long countByExample(TUserPrincipalForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	int deleteByExample(TUserPrincipalForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	int insert(TUserPrincipalForum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	int insertSelective(TUserPrincipalForum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	List<TUserPrincipalForum> selectByExample(TUserPrincipalForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	TUserPrincipalForum selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TUserPrincipalForum record,
			@Param("example") TUserPrincipalForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	int updateByExample(@Param("record") TUserPrincipalForum record,
			@Param("example") TUserPrincipalForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	int updateByPrimaryKeySelective(TUserPrincipalForum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Sat Jul 21 11:56:46 CST 2018
	 */
	int updateByPrimaryKey(TUserPrincipalForum record);
}