package bbs.subscriptionsystem.mapper;

import bbs.subscriptionsystem.action.entity.BaseAction;
import bbs.subscriptionsystem.action.entity.CommodyCommentAction;
import bbs.subscriptionsystem.entity.TCommodyCommentAction;
import bbs.subscriptionsystem.entity.TCommodyCommentActionExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCommodyCommentActionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	long countByExample(TCommodyCommentActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	int deleteByExample(TCommodyCommentActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	int insert(TCommodyCommentAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	int insertSelective(TCommodyCommentAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	List<TCommodyCommentAction> selectByExample(TCommodyCommentActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	TCommodyCommentAction selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TCommodyCommentAction record,
			@Param("example") TCommodyCommentActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	int updateByExample(@Param("record") TCommodyCommentAction record,
			@Param("example") TCommodyCommentActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	int updateByPrimaryKeySelective(TCommodyCommentAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment_action
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	int updateByPrimaryKey(TCommodyCommentAction record);

	List<CommodyCommentAction> selectCommodyCommentActionByCommodyId(long commodyId);
	
	CommodyCommentAction selectCommodyCommentActionById(long actionId);

	List<CommodyCommentAction> selectAllByCommodyIdAfterLastReadTime(@Param("commodyId") Long commodyId,@Param("lastReadTime") Date lastReadTime);

	Integer countByCommodyIdAfterLastReadTime(@Param("commodyId") Long commodyId,@Param("lastReadTime") Date lastReadTime);

	List<? extends BaseAction> selectAllByCommentIdAfterLastReadTime(@Param("commentId") Long commentId,@Param("lastReadTime") Date lastReadTime);

	Integer countByCommentIdAfterLastReadTime(@Param("commentId") Long commentId,@Param("lastReadTime") Date lastReadTime);
}