package bbs.subscriptionsystem.mapper;

import bbs.subscriptionsystem.action.entity.ForumTrendAction;
import bbs.subscriptionsystem.entity.TForumTrendAction;
import bbs.subscriptionsystem.entity.TForumTrendActionExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TForumTrendActionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	long countByExample(TForumTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	int deleteByExample(TForumTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	int insert(TForumTrendAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	int insertSelective(TForumTrendAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	List<TForumTrendAction> selectByExample(TForumTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	TForumTrendAction selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TForumTrendAction record,
			@Param("example") TForumTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	int updateByExample(@Param("record") TForumTrendAction record, @Param("example") TForumTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	int updateByPrimaryKeySelective(TForumTrendAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_forum_trend_action
	 * @mbg.generated  Sun Jul 01 18:39:56 CST 2018
	 */
	int updateByPrimaryKey(TForumTrendAction record);

	List<ForumTrendAction> selectAllForumTrendActionByForumIdAfterLastReadTime(@Param("forumId") Integer forumId, @Param("lastReadTime")Date lastReadTime);
}