package bbs.subscriptionsystem.mapper;

import bbs.subscriptionsystem.entity.TSubscription;
import bbs.subscriptionsystem.entity.TSubscriptionExample;
import bbs.subscriptionsystem.enuma.SubscriptionType;
import bbs.subscriptionsystem.subscription.entity.BaseSubscription;
import bbs.subscriptionsystem.subscription.entity.FollowingSubscription;
import bbs.subscriptionsystem.subscription.entity.ForumSubscription;
import bbs.subscriptionsystem.subscription.entity.TopicSubscription;
import bbs.subscriptionsystem.subscription.entity.PostSubscription;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSubscriptionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	long countByExample(TSubscriptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int deleteByExample(TSubscriptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int insert(TSubscription record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int insertSelective(TSubscription record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	List<TSubscription> selectByExample(TSubscriptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	TSubscription selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TSubscription record, @Param("example") TSubscriptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int updateByExample(@Param("record") TSubscription record, @Param("example") TSubscriptionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int updateByPrimaryKeySelective(TSubscription record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int updateByPrimaryKey(TSubscription record);

	List<? extends BaseSubscription<?>> selectAllByUid(long uid);

	List<TopicSubscription> selectAllTopicSubscriptionByUid(long uid);

	List<PostSubscription> selectAllPostSubscriptionByUid(long uid);

	List<ForumSubscription> selectAllForumSubscriptionByUid(long uid);

	void deleteByUidAndTargetId(@Param("userId") long uid,@Param("targetId") long targetId, @Param("subscriptionType") SubscriptionType subscriptionType);

	int countSubscriptionByUidAndTargetIdAndType(@Param("userId")long uid,@Param("targetId") long targetId,@Param("subscriptionType") SubscriptionType subscriptionType);
}