package bbs.subscriptionsystem.mapper;

import bbs.helper.PageParam;
import bbs.subscriptionsystem.action.entity.TopicTrendAction;
import bbs.subscriptionsystem.entity.TTopicTrendAction;
import bbs.subscriptionsystem.entity.TTopicTrendActionExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTopicTrendActionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	long countByExample(TTopicTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int deleteByExample(TTopicTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int insert(TTopicTrendAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int insertSelective(TTopicTrendAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	List<TTopicTrendAction> selectByExample(TTopicTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	TTopicTrendAction selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TTopicTrendAction record,
			@Param("example") TTopicTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int updateByExample(@Param("record") TTopicTrendAction record, @Param("example") TTopicTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int updateByPrimaryKeySelective(TTopicTrendAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic_trend_action
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	int updateByPrimaryKey(TTopicTrendAction record);

	List<TTopicTrendAction> selectAfterLastReadTime(long topicId, Date lastReadTime);

	List<TopicTrendAction> selectAllByTopicIdAfterLastReadTime(@Param("topicId") long topicId,@Param("lastReadTime") Date lastReadTime);

	TopicTrendAction selectTopicTrendActionById(long actionId);

	Integer countByTopicIdAfterLastReadTime(@Param("topicId") long topicId,@Param("lastReadTime") Date lastReadTime);
}