package bbs.subscriptionsystem.mapper;

import bbs.form.utils.PageParam;
import bbs.forum.DTO.User;
import bbs.subscriptionsystem.action.entity.CollectUserAction;
import bbs.subscriptionsystem.action.entity.UserTrendAction;
import bbs.subscriptionsystem.entity.TUserTrendAction;
import bbs.subscriptionsystem.entity.TUserTrendActionExample;
import bbs.subscriptionsystem.enuma.UserTrendActionTargetType;
import bbs.subscriptionsystem.enuma.UserTrendActionType;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserTrendActionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	long countByExample(TUserTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	int deleteByExample(TUserTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	int insert(TUserTrendAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	int insertSelective(TUserTrendAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	List<TUserTrendAction> selectByExample(TUserTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	TUserTrendAction selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TUserTrendAction record,
			@Param("example") TUserTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	int updateByExample(@Param("record") TUserTrendAction record, @Param("example") TUserTrendActionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	int updateByPrimaryKeySelective(TUserTrendAction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_trend_action
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	int updateByPrimaryKey(TUserTrendAction record);

	List<TUserTrendAction> selectByIdAfterLastReadTime(long uid, Date lastReadTime);

	List<TUserTrendAction> selectByUid(long uid);
	
	List<UserTrendAction<?>> selectAllUidAfterLastReadTime(@Param("userId")long uid, 
			@Param("lastReadTime") Date lastReadTime,
			@Param("actionType") UserTrendActionType actionType, 
			@Param("targetType") UserTrendActionTargetType targetType);

	UserTrendAction<?> selectUserTrendActionById(long actionId);

	Integer countUidAfterLastReadTime(@Param("userId") Long uid,@Param("lastReadTime") Date lastReadTime);

	List<CollectUserAction> selectAllByFollowingIdAfterLastReadTime(@Param("followingId") Long myUid,@Param("lastReadTime") Date lastReadTime);

	Integer countByFollowingIdAfterLastReadTime(@Param("followingId") Long followingId,@Param("lastReadTime") Date lastReadTime);
	
//	List<UserTrendAction<?>> selectAllByUidAfterLastReadTime(@Param("userId")long uid, 
//			@Param("lastReadTime") Date lastReadTime,
//			@Param("pageParam") PageParam pageParam);
}