package bbs.subscriptionsystem.entity;

import java.util.Date;

public class TForumTrendAction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_forum_trend_action.id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_forum_trend_action.forum_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	private Integer forumId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_forum_trend_action.pub_time
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	private Date pubTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_forum_trend_action.publisher_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	private Long publisherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_forum_trend_action.announce_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	private Integer announceId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_forum_trend_action.id
	 * @return  the value of t_forum_trend_action.id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_forum_trend_action.id
	 * @param id  the value for t_forum_trend_action.id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_forum_trend_action.forum_id
	 * @return  the value of t_forum_trend_action.forum_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public Integer getForumId() {
		return forumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_forum_trend_action.forum_id
	 * @param forumId  the value for t_forum_trend_action.forum_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public void setForumId(Integer forumId) {
		this.forumId = forumId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_forum_trend_action.pub_time
	 * @return  the value of t_forum_trend_action.pub_time
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public Date getPubTime() {
		return pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_forum_trend_action.pub_time
	 * @param pubTime  the value for t_forum_trend_action.pub_time
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_forum_trend_action.publisher_id
	 * @return  the value of t_forum_trend_action.publisher_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public Long getPublisherId() {
		return publisherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_forum_trend_action.publisher_id
	 * @param publisherId  the value for t_forum_trend_action.publisher_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public void setPublisherId(Long publisherId) {
		this.publisherId = publisherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_forum_trend_action.announce_id
	 * @return  the value of t_forum_trend_action.announce_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public Integer getAnnounceId() {
		return announceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_forum_trend_action.announce_id
	 * @param announceId  the value for t_forum_trend_action.announce_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public void setAnnounceId(Integer announceId) {
		this.announceId = announceId;
	}
}