package bbs.subscriptionsystem.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TNoticeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public TNoticeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPubTimeIsNull() {
			addCriterion("pub_time is null");
			return (Criteria) this;
		}

		public Criteria andPubTimeIsNotNull() {
			addCriterion("pub_time is not null");
			return (Criteria) this;
		}

		public Criteria andPubTimeEqualTo(Date value) {
			addCriterion("pub_time =", value, "pubTime");
			return (Criteria) this;
		}

		public Criteria andPubTimeNotEqualTo(Date value) {
			addCriterion("pub_time <>", value, "pubTime");
			return (Criteria) this;
		}

		public Criteria andPubTimeGreaterThan(Date value) {
			addCriterion("pub_time >", value, "pubTime");
			return (Criteria) this;
		}

		public Criteria andPubTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("pub_time >=", value, "pubTime");
			return (Criteria) this;
		}

		public Criteria andPubTimeLessThan(Date value) {
			addCriterion("pub_time <", value, "pubTime");
			return (Criteria) this;
		}

		public Criteria andPubTimeLessThanOrEqualTo(Date value) {
			addCriterion("pub_time <=", value, "pubTime");
			return (Criteria) this;
		}

		public Criteria andPubTimeIn(List<Date> values) {
			addCriterion("pub_time in", values, "pubTime");
			return (Criteria) this;
		}

		public Criteria andPubTimeNotIn(List<Date> values) {
			addCriterion("pub_time not in", values, "pubTime");
			return (Criteria) this;
		}

		public Criteria andPubTimeBetween(Date value1, Date value2) {
			addCriterion("pub_time between", value1, value2, "pubTime");
			return (Criteria) this;
		}

		public Criteria andPubTimeNotBetween(Date value1, Date value2) {
			addCriterion("pub_time not between", value1, value2, "pubTime");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNull() {
			addCriterion("subject is null");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNotNull() {
			addCriterion("subject is not null");
			return (Criteria) this;
		}

		public Criteria andSubjectEqualTo(String value) {
			addCriterion("subject =", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotEqualTo(String value) {
			addCriterion("subject <>", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThan(String value) {
			addCriterion("subject >", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThanOrEqualTo(String value) {
			addCriterion("subject >=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThan(String value) {
			addCriterion("subject <", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThanOrEqualTo(String value) {
			addCriterion("subject <=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLike(String value) {
			addCriterion("subject like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotLike(String value) {
			addCriterion("subject not like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectIn(List<String> values) {
			addCriterion("subject in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotIn(List<String> values) {
			addCriterion("subject not in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectBetween(String value1, String value2) {
			addCriterion("subject between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotBetween(String value1, String value2) {
			addCriterion("subject not between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andPredicateIsNull() {
			addCriterion("predicate is null");
			return (Criteria) this;
		}

		public Criteria andPredicateIsNotNull() {
			addCriterion("predicate is not null");
			return (Criteria) this;
		}

		public Criteria andPredicateEqualTo(String value) {
			addCriterion("predicate =", value, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateNotEqualTo(String value) {
			addCriterion("predicate <>", value, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateGreaterThan(String value) {
			addCriterion("predicate >", value, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateGreaterThanOrEqualTo(String value) {
			addCriterion("predicate >=", value, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateLessThan(String value) {
			addCriterion("predicate <", value, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateLessThanOrEqualTo(String value) {
			addCriterion("predicate <=", value, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateLike(String value) {
			addCriterion("predicate like", value, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateNotLike(String value) {
			addCriterion("predicate not like", value, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateIn(List<String> values) {
			addCriterion("predicate in", values, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateNotIn(List<String> values) {
			addCriterion("predicate not in", values, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateBetween(String value1, String value2) {
			addCriterion("predicate between", value1, value2, "predicate");
			return (Criteria) this;
		}

		public Criteria andPredicateNotBetween(String value1, String value2) {
			addCriterion("predicate not between", value1, value2, "predicate");
			return (Criteria) this;
		}

		public Criteria andObjectIsNull() {
			addCriterion("object is null");
			return (Criteria) this;
		}

		public Criteria andObjectIsNotNull() {
			addCriterion("object is not null");
			return (Criteria) this;
		}

		public Criteria andObjectEqualTo(String value) {
			addCriterion("object =", value, "object");
			return (Criteria) this;
		}

		public Criteria andObjectNotEqualTo(String value) {
			addCriterion("object <>", value, "object");
			return (Criteria) this;
		}

		public Criteria andObjectGreaterThan(String value) {
			addCriterion("object >", value, "object");
			return (Criteria) this;
		}

		public Criteria andObjectGreaterThanOrEqualTo(String value) {
			addCriterion("object >=", value, "object");
			return (Criteria) this;
		}

		public Criteria andObjectLessThan(String value) {
			addCriterion("object <", value, "object");
			return (Criteria) this;
		}

		public Criteria andObjectLessThanOrEqualTo(String value) {
			addCriterion("object <=", value, "object");
			return (Criteria) this;
		}

		public Criteria andObjectLike(String value) {
			addCriterion("object like", value, "object");
			return (Criteria) this;
		}

		public Criteria andObjectNotLike(String value) {
			addCriterion("object not like", value, "object");
			return (Criteria) this;
		}

		public Criteria andObjectIn(List<String> values) {
			addCriterion("object in", values, "object");
			return (Criteria) this;
		}

		public Criteria andObjectNotIn(List<String> values) {
			addCriterion("object not in", values, "object");
			return (Criteria) this;
		}

		public Criteria andObjectBetween(String value1, String value2) {
			addCriterion("object between", value1, value2, "object");
			return (Criteria) this;
		}

		public Criteria andObjectNotBetween(String value1, String value2) {
			addCriterion("object not between", value1, value2, "object");
			return (Criteria) this;
		}

		public Criteria andAttributeIsNull() {
			addCriterion("attribute is null");
			return (Criteria) this;
		}

		public Criteria andAttributeIsNotNull() {
			addCriterion("attribute is not null");
			return (Criteria) this;
		}

		public Criteria andAttributeEqualTo(String value) {
			addCriterion("attribute =", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeNotEqualTo(String value) {
			addCriterion("attribute <>", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeGreaterThan(String value) {
			addCriterion("attribute >", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeGreaterThanOrEqualTo(String value) {
			addCriterion("attribute >=", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeLessThan(String value) {
			addCriterion("attribute <", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeLessThanOrEqualTo(String value) {
			addCriterion("attribute <=", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeLike(String value) {
			addCriterion("attribute like", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeNotLike(String value) {
			addCriterion("attribute not like", value, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeIn(List<String> values) {
			addCriterion("attribute in", values, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeNotIn(List<String> values) {
			addCriterion("attribute not in", values, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeBetween(String value1, String value2) {
			addCriterion("attribute between", value1, value2, "attribute");
			return (Criteria) this;
		}

		public Criteria andAttributeNotBetween(String value1, String value2) {
			addCriterion("attribute not between", value1, value2, "attribute");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_notice
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_notice
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 12 21:48:44 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}