package bbs.subscriptionsystem.entity;

import java.util.Date;

public class TNotice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.id
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.pub_time
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	private Date pubTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.subject
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.predicate
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	private String predicate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.object
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	private String object;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.attribute
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	private String attribute;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.id
	 * @return  the value of t_notice.id
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.id
	 * @param id  the value for t_notice.id
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.pub_time
	 * @return  the value of t_notice.pub_time
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public Date getPubTime() {
		return pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.pub_time
	 * @param pubTime  the value for t_notice.pub_time
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.subject
	 * @return  the value of t_notice.subject
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.subject
	 * @param subject  the value for t_notice.subject
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.predicate
	 * @return  the value of t_notice.predicate
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public String getPredicate() {
		return predicate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.predicate
	 * @param predicate  the value for t_notice.predicate
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public void setPredicate(String predicate) {
		this.predicate = predicate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.object
	 * @return  the value of t_notice.object
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public String getObject() {
		return object;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.object
	 * @param object  the value for t_notice.object
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public void setObject(String object) {
		this.object = object;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.attribute
	 * @return  the value of t_notice.attribute
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public String getAttribute() {
		return attribute;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.attribute
	 * @param attribute  the value for t_notice.attribute
	 * @mbg.generated  Wed Jun 20 15:57:04 CST 2018
	 */
	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}
}