package bbs.subscriptionsystem.entity;

import bbs.subscriptionsystem.enuma.SubscriptionType;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSubscriptionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public TSubscriptionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> subscriptionTypeCriteria;
		protected List<Criterion> allCriteria;
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
			subscriptionTypeCriteria = new ArrayList<Criterion>();
		}

		public List<Criterion> getSubscriptionTypeCriteria() {
			return subscriptionTypeCriteria;
		}

		protected void addSubscriptionTypeCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			subscriptionTypeCriteria
					.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumOrdinalTypeHandler"));
			allCriteria = null;
		}

		protected void addSubscriptionTypeCriterion(String condition, SubscriptionType value1, SubscriptionType value2,
				String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			subscriptionTypeCriteria
					.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumOrdinalTypeHandler"));
			allCriteria = null;
		}

		public boolean isValid() {
			return criteria.size() > 0 || subscriptionTypeCriteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			if (allCriteria == null) {
				allCriteria = new ArrayList<Criterion>();
				allCriteria.addAll(criteria);
				allCriteria.addAll(subscriptionTypeCriteria);
			}
			return allCriteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
			allCriteria = null;
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
			allCriteria = null;
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
			allCriteria = null;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeIsNull() {
			addCriterion("last_read_time is null");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeIsNotNull() {
			addCriterion("last_read_time is not null");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeEqualTo(Date value) {
			addCriterion("last_read_time =", value, "lastReadTime");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeNotEqualTo(Date value) {
			addCriterion("last_read_time <>", value, "lastReadTime");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeGreaterThan(Date value) {
			addCriterion("last_read_time >", value, "lastReadTime");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("last_read_time >=", value, "lastReadTime");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeLessThan(Date value) {
			addCriterion("last_read_time <", value, "lastReadTime");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeLessThanOrEqualTo(Date value) {
			addCriterion("last_read_time <=", value, "lastReadTime");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeIn(List<Date> values) {
			addCriterion("last_read_time in", values, "lastReadTime");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeNotIn(List<Date> values) {
			addCriterion("last_read_time not in", values, "lastReadTime");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeBetween(Date value1, Date value2) {
			addCriterion("last_read_time between", value1, value2, "lastReadTime");
			return (Criteria) this;
		}

		public Criteria andLastReadTimeNotBetween(Date value1, Date value2) {
			addCriterion("last_read_time not between", value1, value2, "lastReadTime");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeIsNull() {
			addCriterion("subscription_type is null");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeIsNotNull() {
			addCriterion("subscription_type is not null");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeEqualTo(SubscriptionType value) {
			addSubscriptionTypeCriterion("subscription_type =", value, "subscriptionType");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeNotEqualTo(SubscriptionType value) {
			addSubscriptionTypeCriterion("subscription_type <>", value, "subscriptionType");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeGreaterThan(SubscriptionType value) {
			addSubscriptionTypeCriterion("subscription_type >", value, "subscriptionType");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeGreaterThanOrEqualTo(SubscriptionType value) {
			addSubscriptionTypeCriterion("subscription_type >=", value, "subscriptionType");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeLessThan(SubscriptionType value) {
			addSubscriptionTypeCriterion("subscription_type <", value, "subscriptionType");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeLessThanOrEqualTo(SubscriptionType value) {
			addSubscriptionTypeCriterion("subscription_type <=", value, "subscriptionType");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeIn(List<SubscriptionType> values) {
			addSubscriptionTypeCriterion("subscription_type in", values, "subscriptionType");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeNotIn(List<SubscriptionType> values) {
			addSubscriptionTypeCriterion("subscription_type not in", values, "subscriptionType");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeBetween(SubscriptionType value1, SubscriptionType value2) {
			addSubscriptionTypeCriterion("subscription_type between", value1, value2, "subscriptionType");
			return (Criteria) this;
		}

		public Criteria andSubscriptionTypeNotBetween(SubscriptionType value1, SubscriptionType value2) {
			addSubscriptionTypeCriterion("subscription_type not between", value1, value2, "subscriptionType");
			return (Criteria) this;
		}

		public Criteria andFollowingIdIsNull() {
			addCriterion("following_id is null");
			return (Criteria) this;
		}

		public Criteria andFollowingIdIsNotNull() {
			addCriterion("following_id is not null");
			return (Criteria) this;
		}

		public Criteria andFollowingIdEqualTo(Long value) {
			addCriterion("following_id =", value, "followingId");
			return (Criteria) this;
		}

		public Criteria andFollowingIdNotEqualTo(Long value) {
			addCriterion("following_id <>", value, "followingId");
			return (Criteria) this;
		}

		public Criteria andFollowingIdGreaterThan(Long value) {
			addCriterion("following_id >", value, "followingId");
			return (Criteria) this;
		}

		public Criteria andFollowingIdGreaterThanOrEqualTo(Long value) {
			addCriterion("following_id >=", value, "followingId");
			return (Criteria) this;
		}

		public Criteria andFollowingIdLessThan(Long value) {
			addCriterion("following_id <", value, "followingId");
			return (Criteria) this;
		}

		public Criteria andFollowingIdLessThanOrEqualTo(Long value) {
			addCriterion("following_id <=", value, "followingId");
			return (Criteria) this;
		}

		public Criteria andFollowingIdIn(List<Long> values) {
			addCriterion("following_id in", values, "followingId");
			return (Criteria) this;
		}

		public Criteria andFollowingIdNotIn(List<Long> values) {
			addCriterion("following_id not in", values, "followingId");
			return (Criteria) this;
		}

		public Criteria andFollowingIdBetween(Long value1, Long value2) {
			addCriterion("following_id between", value1, value2, "followingId");
			return (Criteria) this;
		}

		public Criteria andFollowingIdNotBetween(Long value1, Long value2) {
			addCriterion("following_id not between", value1, value2, "followingId");
			return (Criteria) this;
		}

		public Criteria andForumIdIsNull() {
			addCriterion("forum_id is null");
			return (Criteria) this;
		}

		public Criteria andForumIdIsNotNull() {
			addCriterion("forum_id is not null");
			return (Criteria) this;
		}

		public Criteria andForumIdEqualTo(Integer value) {
			addCriterion("forum_id =", value, "forumId");
			return (Criteria) this;
		}

		public Criteria andForumIdNotEqualTo(Integer value) {
			addCriterion("forum_id <>", value, "forumId");
			return (Criteria) this;
		}

		public Criteria andForumIdGreaterThan(Integer value) {
			addCriterion("forum_id >", value, "forumId");
			return (Criteria) this;
		}

		public Criteria andForumIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("forum_id >=", value, "forumId");
			return (Criteria) this;
		}

		public Criteria andForumIdLessThan(Integer value) {
			addCriterion("forum_id <", value, "forumId");
			return (Criteria) this;
		}

		public Criteria andForumIdLessThanOrEqualTo(Integer value) {
			addCriterion("forum_id <=", value, "forumId");
			return (Criteria) this;
		}

		public Criteria andForumIdIn(List<Integer> values) {
			addCriterion("forum_id in", values, "forumId");
			return (Criteria) this;
		}

		public Criteria andForumIdNotIn(List<Integer> values) {
			addCriterion("forum_id not in", values, "forumId");
			return (Criteria) this;
		}

		public Criteria andForumIdBetween(Integer value1, Integer value2) {
			addCriterion("forum_id between", value1, value2, "forumId");
			return (Criteria) this;
		}

		public Criteria andForumIdNotBetween(Integer value1, Integer value2) {
			addCriterion("forum_id not between", value1, value2, "forumId");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeIsNull() {
			addCriterion("subscribe_time is null");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeIsNotNull() {
			addCriterion("subscribe_time is not null");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeEqualTo(Date value) {
			addCriterion("subscribe_time =", value, "subscribeTime");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeNotEqualTo(Date value) {
			addCriterion("subscribe_time <>", value, "subscribeTime");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeGreaterThan(Date value) {
			addCriterion("subscribe_time >", value, "subscribeTime");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("subscribe_time >=", value, "subscribeTime");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeLessThan(Date value) {
			addCriterion("subscribe_time <", value, "subscribeTime");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeLessThanOrEqualTo(Date value) {
			addCriterion("subscribe_time <=", value, "subscribeTime");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeIn(List<Date> values) {
			addCriterion("subscribe_time in", values, "subscribeTime");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeNotIn(List<Date> values) {
			addCriterion("subscribe_time not in", values, "subscribeTime");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeBetween(Date value1, Date value2) {
			addCriterion("subscribe_time between", value1, value2, "subscribeTime");
			return (Criteria) this;
		}

		public Criteria andSubscribeTimeNotBetween(Date value1, Date value2) {
			addCriterion("subscribe_time not between", value1, value2, "subscribeTime");
			return (Criteria) this;
		}

		public Criteria andTopicIdIsNull() {
			addCriterion("topic_id is null");
			return (Criteria) this;
		}

		public Criteria andTopicIdIsNotNull() {
			addCriterion("topic_id is not null");
			return (Criteria) this;
		}

		public Criteria andTopicIdEqualTo(Long value) {
			addCriterion("topic_id =", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdNotEqualTo(Long value) {
			addCriterion("topic_id <>", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdGreaterThan(Long value) {
			addCriterion("topic_id >", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdGreaterThanOrEqualTo(Long value) {
			addCriterion("topic_id >=", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdLessThan(Long value) {
			addCriterion("topic_id <", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdLessThanOrEqualTo(Long value) {
			addCriterion("topic_id <=", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdIn(List<Long> values) {
			addCriterion("topic_id in", values, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdNotIn(List<Long> values) {
			addCriterion("topic_id not in", values, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdBetween(Long value1, Long value2) {
			addCriterion("topic_id between", value1, value2, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdNotBetween(Long value1, Long value2) {
			addCriterion("topic_id not between", value1, value2, "topicId");
			return (Criteria) this;
		}

		public Criteria andPostIdIsNull() {
			addCriterion("post_id is null");
			return (Criteria) this;
		}

		public Criteria andPostIdIsNotNull() {
			addCriterion("post_id is not null");
			return (Criteria) this;
		}

		public Criteria andPostIdEqualTo(Long value) {
			addCriterion("post_id =", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdNotEqualTo(Long value) {
			addCriterion("post_id <>", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdGreaterThan(Long value) {
			addCriterion("post_id >", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdGreaterThanOrEqualTo(Long value) {
			addCriterion("post_id >=", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdLessThan(Long value) {
			addCriterion("post_id <", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdLessThanOrEqualTo(Long value) {
			addCriterion("post_id <=", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdIn(List<Long> values) {
			addCriterion("post_id in", values, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdNotIn(List<Long> values) {
			addCriterion("post_id not in", values, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdBetween(Long value1, Long value2) {
			addCriterion("post_id between", value1, value2, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdNotBetween(Long value1, Long value2) {
			addCriterion("post_id not between", value1, value2, "postId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_subscription
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_subscription
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 12 21:48:44 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}