package bbs.subscriptionsystem.entity;

public class TSubscriptionConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_subscription_config.id
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_subscription_config.like_topic
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	private Byte likeTopic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_subscription_config.like_post
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	private Byte likePost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_subscription_config.pub_topic
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	private Byte pubTopic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_subscription_config.pub_post
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	private Byte pubPost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_subscription_config.user_id
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	private Long userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_subscription_config.id
	 * @return  the value of t_subscription_config.id
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_subscription_config.id
	 * @param id  the value for t_subscription_config.id
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_subscription_config.like_topic
	 * @return  the value of t_subscription_config.like_topic
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public Byte getLikeTopic() {
		return likeTopic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_subscription_config.like_topic
	 * @param likeTopic  the value for t_subscription_config.like_topic
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public void setLikeTopic(Byte likeTopic) {
		this.likeTopic = likeTopic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_subscription_config.like_post
	 * @return  the value of t_subscription_config.like_post
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public Byte getLikePost() {
		return likePost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_subscription_config.like_post
	 * @param likePost  the value for t_subscription_config.like_post
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public void setLikePost(Byte likePost) {
		this.likePost = likePost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_subscription_config.pub_topic
	 * @return  the value of t_subscription_config.pub_topic
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public Byte getPubTopic() {
		return pubTopic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_subscription_config.pub_topic
	 * @param pubTopic  the value for t_subscription_config.pub_topic
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public void setPubTopic(Byte pubTopic) {
		this.pubTopic = pubTopic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_subscription_config.pub_post
	 * @return  the value of t_subscription_config.pub_post
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public Byte getPubPost() {
		return pubPost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_subscription_config.pub_post
	 * @param pubPost  the value for t_subscription_config.pub_post
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public void setPubPost(Byte pubPost) {
		this.pubPost = pubPost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_subscription_config.user_id
	 * @return  the value of t_subscription_config.user_id
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_subscription_config.user_id
	 * @param userId  the value for t_subscription_config.user_id
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}
}