package bbs.subscriptionsystem.entity;

import java.util.ArrayList;
import java.util.List;

public class TSubscriptionConfigExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public TSubscriptionConfigExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andLikeTopicIsNull() {
			addCriterion("like_topic is null");
			return (Criteria) this;
		}

		public Criteria andLikeTopicIsNotNull() {
			addCriterion("like_topic is not null");
			return (Criteria) this;
		}

		public Criteria andLikeTopicEqualTo(Byte value) {
			addCriterion("like_topic =", value, "likeTopic");
			return (Criteria) this;
		}

		public Criteria andLikeTopicNotEqualTo(Byte value) {
			addCriterion("like_topic <>", value, "likeTopic");
			return (Criteria) this;
		}

		public Criteria andLikeTopicGreaterThan(Byte value) {
			addCriterion("like_topic >", value, "likeTopic");
			return (Criteria) this;
		}

		public Criteria andLikeTopicGreaterThanOrEqualTo(Byte value) {
			addCriterion("like_topic >=", value, "likeTopic");
			return (Criteria) this;
		}

		public Criteria andLikeTopicLessThan(Byte value) {
			addCriterion("like_topic <", value, "likeTopic");
			return (Criteria) this;
		}

		public Criteria andLikeTopicLessThanOrEqualTo(Byte value) {
			addCriterion("like_topic <=", value, "likeTopic");
			return (Criteria) this;
		}

		public Criteria andLikeTopicIn(List<Byte> values) {
			addCriterion("like_topic in", values, "likeTopic");
			return (Criteria) this;
		}

		public Criteria andLikeTopicNotIn(List<Byte> values) {
			addCriterion("like_topic not in", values, "likeTopic");
			return (Criteria) this;
		}

		public Criteria andLikeTopicBetween(Byte value1, Byte value2) {
			addCriterion("like_topic between", value1, value2, "likeTopic");
			return (Criteria) this;
		}

		public Criteria andLikeTopicNotBetween(Byte value1, Byte value2) {
			addCriterion("like_topic not between", value1, value2, "likeTopic");
			return (Criteria) this;
		}

		public Criteria andLikePostIsNull() {
			addCriterion("like_post is null");
			return (Criteria) this;
		}

		public Criteria andLikePostIsNotNull() {
			addCriterion("like_post is not null");
			return (Criteria) this;
		}

		public Criteria andLikePostEqualTo(Byte value) {
			addCriterion("like_post =", value, "likePost");
			return (Criteria) this;
		}

		public Criteria andLikePostNotEqualTo(Byte value) {
			addCriterion("like_post <>", value, "likePost");
			return (Criteria) this;
		}

		public Criteria andLikePostGreaterThan(Byte value) {
			addCriterion("like_post >", value, "likePost");
			return (Criteria) this;
		}

		public Criteria andLikePostGreaterThanOrEqualTo(Byte value) {
			addCriterion("like_post >=", value, "likePost");
			return (Criteria) this;
		}

		public Criteria andLikePostLessThan(Byte value) {
			addCriterion("like_post <", value, "likePost");
			return (Criteria) this;
		}

		public Criteria andLikePostLessThanOrEqualTo(Byte value) {
			addCriterion("like_post <=", value, "likePost");
			return (Criteria) this;
		}

		public Criteria andLikePostIn(List<Byte> values) {
			addCriterion("like_post in", values, "likePost");
			return (Criteria) this;
		}

		public Criteria andLikePostNotIn(List<Byte> values) {
			addCriterion("like_post not in", values, "likePost");
			return (Criteria) this;
		}

		public Criteria andLikePostBetween(Byte value1, Byte value2) {
			addCriterion("like_post between", value1, value2, "likePost");
			return (Criteria) this;
		}

		public Criteria andLikePostNotBetween(Byte value1, Byte value2) {
			addCriterion("like_post not between", value1, value2, "likePost");
			return (Criteria) this;
		}

		public Criteria andPubTopicIsNull() {
			addCriterion("pub_topic is null");
			return (Criteria) this;
		}

		public Criteria andPubTopicIsNotNull() {
			addCriterion("pub_topic is not null");
			return (Criteria) this;
		}

		public Criteria andPubTopicEqualTo(Byte value) {
			addCriterion("pub_topic =", value, "pubTopic");
			return (Criteria) this;
		}

		public Criteria andPubTopicNotEqualTo(Byte value) {
			addCriterion("pub_topic <>", value, "pubTopic");
			return (Criteria) this;
		}

		public Criteria andPubTopicGreaterThan(Byte value) {
			addCriterion("pub_topic >", value, "pubTopic");
			return (Criteria) this;
		}

		public Criteria andPubTopicGreaterThanOrEqualTo(Byte value) {
			addCriterion("pub_topic >=", value, "pubTopic");
			return (Criteria) this;
		}

		public Criteria andPubTopicLessThan(Byte value) {
			addCriterion("pub_topic <", value, "pubTopic");
			return (Criteria) this;
		}

		public Criteria andPubTopicLessThanOrEqualTo(Byte value) {
			addCriterion("pub_topic <=", value, "pubTopic");
			return (Criteria) this;
		}

		public Criteria andPubTopicIn(List<Byte> values) {
			addCriterion("pub_topic in", values, "pubTopic");
			return (Criteria) this;
		}

		public Criteria andPubTopicNotIn(List<Byte> values) {
			addCriterion("pub_topic not in", values, "pubTopic");
			return (Criteria) this;
		}

		public Criteria andPubTopicBetween(Byte value1, Byte value2) {
			addCriterion("pub_topic between", value1, value2, "pubTopic");
			return (Criteria) this;
		}

		public Criteria andPubTopicNotBetween(Byte value1, Byte value2) {
			addCriterion("pub_topic not between", value1, value2, "pubTopic");
			return (Criteria) this;
		}

		public Criteria andPubPostIsNull() {
			addCriterion("pub_post is null");
			return (Criteria) this;
		}

		public Criteria andPubPostIsNotNull() {
			addCriterion("pub_post is not null");
			return (Criteria) this;
		}

		public Criteria andPubPostEqualTo(Byte value) {
			addCriterion("pub_post =", value, "pubPost");
			return (Criteria) this;
		}

		public Criteria andPubPostNotEqualTo(Byte value) {
			addCriterion("pub_post <>", value, "pubPost");
			return (Criteria) this;
		}

		public Criteria andPubPostGreaterThan(Byte value) {
			addCriterion("pub_post >", value, "pubPost");
			return (Criteria) this;
		}

		public Criteria andPubPostGreaterThanOrEqualTo(Byte value) {
			addCriterion("pub_post >=", value, "pubPost");
			return (Criteria) this;
		}

		public Criteria andPubPostLessThan(Byte value) {
			addCriterion("pub_post <", value, "pubPost");
			return (Criteria) this;
		}

		public Criteria andPubPostLessThanOrEqualTo(Byte value) {
			addCriterion("pub_post <=", value, "pubPost");
			return (Criteria) this;
		}

		public Criteria andPubPostIn(List<Byte> values) {
			addCriterion("pub_post in", values, "pubPost");
			return (Criteria) this;
		}

		public Criteria andPubPostNotIn(List<Byte> values) {
			addCriterion("pub_post not in", values, "pubPost");
			return (Criteria) this;
		}

		public Criteria andPubPostBetween(Byte value1, Byte value2) {
			addCriterion("pub_post between", value1, value2, "pubPost");
			return (Criteria) this;
		}

		public Criteria andPubPostNotBetween(Byte value1, Byte value2) {
			addCriterion("pub_post not between", value1, value2, "pubPost");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_subscription_config
	 * @mbg.generated  Tue Jul 17 18:29:10 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_subscription_config
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 12 21:48:44 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}