package bbs.subscriptionsystem.entity;

import java.util.Date;

public class TTopicTrendAction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic_trend_action.id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic_trend_action.pub_time
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	private Date pubTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic_trend_action.reply_post_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	private Long replyPostId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic_trend_action.topic_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	private Long topicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_topic_trend_action.replier_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	private Long replierId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic_trend_action.id
	 * @return  the value of t_topic_trend_action.id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic_trend_action.id
	 * @param id  the value for t_topic_trend_action.id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic_trend_action.pub_time
	 * @return  the value of t_topic_trend_action.pub_time
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public Date getPubTime() {
		return pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic_trend_action.pub_time
	 * @param pubTime  the value for t_topic_trend_action.pub_time
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic_trend_action.reply_post_id
	 * @return  the value of t_topic_trend_action.reply_post_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public Long getReplyPostId() {
		return replyPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic_trend_action.reply_post_id
	 * @param replyPostId  the value for t_topic_trend_action.reply_post_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public void setReplyPostId(Long replyPostId) {
		this.replyPostId = replyPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic_trend_action.topic_id
	 * @return  the value of t_topic_trend_action.topic_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public Long getTopicId() {
		return topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic_trend_action.topic_id
	 * @param topicId  the value for t_topic_trend_action.topic_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public void setTopicId(Long topicId) {
		this.topicId = topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_topic_trend_action.replier_id
	 * @return  the value of t_topic_trend_action.replier_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public Long getReplierId() {
		return replierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_topic_trend_action.replier_id
	 * @param replierId  the value for t_topic_trend_action.replier_id
	 * @mbg.generated  Thu Jul 26 22:08:32 CST 2018
	 */
	public void setReplierId(Long replierId) {
		this.replierId = replierId;
	}
}