package bbs.subscriptionsystem.entity;

import bbs.subscriptionsystem.enuma.UserTrendActionTargetType;
import bbs.subscriptionsystem.enuma.UserTrendActionType;
import java.util.Date;

public class TUserTrendAction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_trend_action.id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_trend_action.action_type
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	private UserTrendActionType actionType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_trend_action.target_type
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	private UserTrendActionTargetType targetType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_trend_action.user_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_trend_action.pub_time
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	private Date pubTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_trend_action.following_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	private Long followingId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_trend_action.topic_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	private Long topicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_trend_action.post_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	private Long postId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_trend_action.id
	 * @return  the value of t_user_trend_action.id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_trend_action.id
	 * @param id  the value for t_user_trend_action.id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_trend_action.action_type
	 * @return  the value of t_user_trend_action.action_type
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public UserTrendActionType getActionType() {
		return actionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_trend_action.action_type
	 * @param actionType  the value for t_user_trend_action.action_type
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void setActionType(UserTrendActionType actionType) {
		this.actionType = actionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_trend_action.target_type
	 * @return  the value of t_user_trend_action.target_type
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public UserTrendActionTargetType getTargetType() {
		return targetType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_trend_action.target_type
	 * @param targetType  the value for t_user_trend_action.target_type
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void setTargetType(UserTrendActionTargetType targetType) {
		this.targetType = targetType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_trend_action.user_id
	 * @return  the value of t_user_trend_action.user_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_trend_action.user_id
	 * @param userId  the value for t_user_trend_action.user_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_trend_action.pub_time
	 * @return  the value of t_user_trend_action.pub_time
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public Date getPubTime() {
		return pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_trend_action.pub_time
	 * @param pubTime  the value for t_user_trend_action.pub_time
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_trend_action.following_id
	 * @return  the value of t_user_trend_action.following_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public Long getFollowingId() {
		return followingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_trend_action.following_id
	 * @param followingId  the value for t_user_trend_action.following_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void setFollowingId(Long followingId) {
		this.followingId = followingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_trend_action.topic_id
	 * @return  the value of t_user_trend_action.topic_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public Long getTopicId() {
		return topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_trend_action.topic_id
	 * @param topicId  the value for t_user_trend_action.topic_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void setTopicId(Long topicId) {
		this.topicId = topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_trend_action.post_id
	 * @return  the value of t_user_trend_action.post_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public Long getPostId() {
		return postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_trend_action.post_id
	 * @param postId  the value for t_user_trend_action.post_id
	 * @mbg.generated  Fri Jul 20 03:03:45 CST 2018
	 */
	public void setPostId(Long postId) {
		this.postId = postId;
	}
}