package bbs.shop.mybatis.entity;

public class TCommodyImg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody_img.id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody_img.filename
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	private String filename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody_img.commody_id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	private Long commodyId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody_img.id
	 * @return  the value of t_commody_img.id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody_img.id
	 * @param id  the value for t_commody_img.id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody_img.filename
	 * @return  the value of t_commody_img.filename
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody_img.filename
	 * @param filename  the value for t_commody_img.filename
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody_img.commody_id
	 * @return  the value of t_commody_img.commody_id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public Long getCommodyId() {
		return commodyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody_img.commody_id
	 * @param commodyId  the value for t_commody_img.commody_id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setCommodyId(Long commodyId) {
		this.commodyId = commodyId;
	}
}