package bbs.shop.mybatis.entity;

public class TKeyword {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_keyword.id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_keyword.value
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_keyword.id
	 * @return  the value of t_keyword.id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_keyword.id
	 * @param id  the value for t_keyword.id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_keyword.value
	 * @return  the value of t_keyword.value
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_keyword.value
	 * @param value  the value for t_keyword.value
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setValue(String value) {
		this.value = value;
	}
}