package bbs.shop.mybatis.entity;

public class TSubClass {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_subclass.id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_subclass.name
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_subclass.id
	 * @return  the value of t_subclass.id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_subclass.id
	 * @param id  the value for t_subclass.id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_subclass.name
	 * @return  the value of t_subclass.name
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_subclass.name
	 * @param name  the value for t_subclass.name
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}
}