package bbs.shop.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class TUserPerferenceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public TUserPerferenceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andKeywordIdIsNull() {
			addCriterion("keyword_id is null");
			return (Criteria) this;
		}

		public Criteria andKeywordIdIsNotNull() {
			addCriterion("keyword_id is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordIdEqualTo(Long value) {
			addCriterion("keyword_id =", value, "keywordId");
			return (Criteria) this;
		}

		public Criteria andKeywordIdNotEqualTo(Long value) {
			addCriterion("keyword_id <>", value, "keywordId");
			return (Criteria) this;
		}

		public Criteria andKeywordIdGreaterThan(Long value) {
			addCriterion("keyword_id >", value, "keywordId");
			return (Criteria) this;
		}

		public Criteria andKeywordIdGreaterThanOrEqualTo(Long value) {
			addCriterion("keyword_id >=", value, "keywordId");
			return (Criteria) this;
		}

		public Criteria andKeywordIdLessThan(Long value) {
			addCriterion("keyword_id <", value, "keywordId");
			return (Criteria) this;
		}

		public Criteria andKeywordIdLessThanOrEqualTo(Long value) {
			addCriterion("keyword_id <=", value, "keywordId");
			return (Criteria) this;
		}

		public Criteria andKeywordIdIn(List<Long> values) {
			addCriterion("keyword_id in", values, "keywordId");
			return (Criteria) this;
		}

		public Criteria andKeywordIdNotIn(List<Long> values) {
			addCriterion("keyword_id not in", values, "keywordId");
			return (Criteria) this;
		}

		public Criteria andKeywordIdBetween(Long value1, Long value2) {
			addCriterion("keyword_id between", value1, value2, "keywordId");
			return (Criteria) this;
		}

		public Criteria andKeywordIdNotBetween(Long value1, Long value2) {
			addCriterion("keyword_id not between", value1, value2, "keywordId");
			return (Criteria) this;
		}

		public Criteria andFrequencyIsNull() {
			addCriterion("frequency is null");
			return (Criteria) this;
		}

		public Criteria andFrequencyIsNotNull() {
			addCriterion("frequency is not null");
			return (Criteria) this;
		}

		public Criteria andFrequencyEqualTo(Integer value) {
			addCriterion("frequency =", value, "frequency");
			return (Criteria) this;
		}

		public Criteria andFrequencyNotEqualTo(Integer value) {
			addCriterion("frequency <>", value, "frequency");
			return (Criteria) this;
		}

		public Criteria andFrequencyGreaterThan(Integer value) {
			addCriterion("frequency >", value, "frequency");
			return (Criteria) this;
		}

		public Criteria andFrequencyGreaterThanOrEqualTo(Integer value) {
			addCriterion("frequency >=", value, "frequency");
			return (Criteria) this;
		}

		public Criteria andFrequencyLessThan(Integer value) {
			addCriterion("frequency <", value, "frequency");
			return (Criteria) this;
		}

		public Criteria andFrequencyLessThanOrEqualTo(Integer value) {
			addCriterion("frequency <=", value, "frequency");
			return (Criteria) this;
		}

		public Criteria andFrequencyIn(List<Integer> values) {
			addCriterion("frequency in", values, "frequency");
			return (Criteria) this;
		}

		public Criteria andFrequencyNotIn(List<Integer> values) {
			addCriterion("frequency not in", values, "frequency");
			return (Criteria) this;
		}

		public Criteria andFrequencyBetween(Integer value1, Integer value2) {
			addCriterion("frequency between", value1, value2, "frequency");
			return (Criteria) this;
		}

		public Criteria andFrequencyNotBetween(Integer value1, Integer value2) {
			addCriterion("frequency not between", value1, value2, "frequency");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_perference
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 02 22:21:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}