package bbs.shop.mybatis.entity;

public class TUserPerference extends TUserPerferenceKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_perference.frequency
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	private Integer frequency;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_perference.frequency
	 * @return  the value of t_user_perference.frequency
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public Integer getFrequency() {
		return frequency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_perference.frequency
	 * @param frequency  the value for t_user_perference.frequency
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}
}