package bbs.shop.mybatis.entity;

public class TUserPerferenceKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_perference.user_id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_perference.keyword_id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	private Long keywordId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_perference.user_id
	 * @return  the value of t_user_perference.user_id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_perference.user_id
	 * @param userId  the value for t_user_perference.user_id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_perference.keyword_id
	 * @return  the value of t_user_perference.keyword_id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public Long getKeywordId() {
		return keywordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_perference.keyword_id
	 * @param keywordId  the value for t_user_perference.keyword_id
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	public void setKeywordId(Long keywordId) {
		this.keywordId = keywordId;
	}
}