package bbs.shop.entity;

import java.util.Date;

public class TCommody {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody.id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody.title
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody.description
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody.user_id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody.classification_id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	private Integer classificationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody.pub_time
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	private Date pubTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody.last_modified_time
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	private Date lastModifiedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody.id
	 * @return  the value of t_commody.id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody.id
	 * @param id  the value for t_commody.id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody.title
	 * @return  the value of t_commody.title
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody.title
	 * @param title  the value for t_commody.title
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody.description
	 * @return  the value of t_commody.description
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody.description
	 * @param description  the value for t_commody.description
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody.user_id
	 * @return  the value of t_commody.user_id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody.user_id
	 * @param userId  the value for t_commody.user_id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody.classification_id
	 * @return  the value of t_commody.classification_id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public Integer getClassificationId() {
		return classificationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody.classification_id
	 * @param classificationId  the value for t_commody.classification_id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public void setClassificationId(Integer classificationId) {
		this.classificationId = classificationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody.pub_time
	 * @return  the value of t_commody.pub_time
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public Date getPubTime() {
		return pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody.pub_time
	 * @param pubTime  the value for t_commody.pub_time
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public void setPubTime(Date pubTime) {
		this.pubTime = pubTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody.last_modified_time
	 * @return  the value of t_commody.last_modified_time
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public Date getLastModifiedTime() {
		return lastModifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody.last_modified_time
	 * @param lastModifiedTime  the value for t_commody.last_modified_time
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}
}