package bbs.shop.entity;

public class TCommodyClassification {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody_classification.id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody_classification.name
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_commody_classification.logo_filename
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	private String logoFilename;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody_classification.id
	 * @return  the value of t_commody_classification.id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody_classification.id
	 * @param id  the value for t_commody_classification.id
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody_classification.name
	 * @return  the value of t_commody_classification.name
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody_classification.name
	 * @param name  the value for t_commody_classification.name
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_commody_classification.logo_filename
	 * @return  the value of t_commody_classification.logo_filename
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public String getLogoFilename() {
		return logoFilename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_commody_classification.logo_filename
	 * @param logoFilename  the value for t_commody_classification.logo_filename
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	public void setLogoFilename(String logoFilename) {
		this.logoFilename = logoFilename;
	}
}