package bbs.shop.mybatis.mapper;

import bbs.shop.mybatis.entity.TCommodyImg;
import bbs.shop.mybatis.entity.TCommodyImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCommodyImgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	long countByExample(TCommodyImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByExample(TCommodyImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insert(TCommodyImg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insertSelective(TCommodyImg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	List<TCommodyImg> selectByExample(TCommodyImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	TCommodyImg selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TCommodyImg record, @Param("example") TCommodyImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExample(@Param("record") TCommodyImg record, @Param("example") TCommodyImgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKeySelective(TCommodyImg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_img
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKey(TCommodyImg record);

	void deleteByCommodyId(long commodyId);
}