package bbs.shop.mybatis.mapper;

import bbs.shop.entity.Commody;
import bbs.shop.entity.Keyword;
import bbs.shop.mybatis.entity.TCommody;
import bbs.shop.mybatis.entity.TCommodyExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TCommodyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	long countByExample(TCommodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByExample(TCommodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insert(TCommody record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insertSelective(TCommody record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	List<TCommody> selectByExample(TCommodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	TCommody selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TCommody record, @Param("example") TCommodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExample(@Param("record") TCommody record, @Param("example") TCommodyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKeySelective(TCommody record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKey(TCommody record);

	Commody selectCommodyById(Long commodyId);

	List<Commody> searchCommodyByTitleKey(String titleKey);

	List<Commody> selectHotCommodyListByClassificationId(int classificationId);
	
	List<Commody> selectAllCommodyByKeyword(Keyword keyword);

	void addSubClassToCommody(@Param("subClassId") Integer subClassId,@Param("commodyId") Long commodyId);

	List<Commody> selectAllCommody();

	void updateViews(long commodyId);

	void updateReplies(Long commodyId);

	List<Commody> searchCommodyByClassificationId(Integer classificationId);

	List<Commody> searchCommodyBySubClassId(long subClassId);

	List<Commody> searchCommodyByKeyword(String titleKeyword);

	List<Commody> selectCommodyByUserId(Long userId);

	List<Long> selectCommodyIdByUidInCommodyIdList(Long uid, List<Long> commodyIdList);
}