package bbs.shop.mybatis.mapper;

import bbs.shop.entity.PrimaryCommodyComment;
import bbs.shop.mybatis.entity.TCommodyComment;
import bbs.shop.mybatis.entity.TCommodyCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCommodyCommentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	long countByExample(TCommodyCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByExample(TCommodyCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insert(TCommodyComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insertSelective(TCommodyComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	List<TCommodyComment> selectByExample(TCommodyCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	TCommodyComment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TCommodyComment record,
			@Param("example") TCommodyCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExample(@Param("record") TCommodyComment record, @Param("example") TCommodyCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKeySelective(TCommodyComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_comment
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKey(TCommodyComment record);

	List<PrimaryCommodyComment> selectAllPrimaryCommentByCommodyId(long commentId);

	PrimaryCommodyComment selectPrimaryCommentById(long commentId);
}