package bbs.shop.mybatis.mapper;

import bbs.shop.mybatis.entity.TKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import bbs.shop.entity.Keyword;
import bbs.shop.mybatis.entity.TKeyword;

public interface TKeywordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	long countByExample(TKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByExample(TKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insert(TKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insertSelective(TKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	List<TKeyword> selectByExample(TKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	TKeyword selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TKeyword record, @Param("example") TKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExample(@Param("record") TKeyword record, @Param("example") TKeywordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKeySelective(TKeyword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_keyword
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKey(TKeyword record);

	void associateKeywordToCommody(@Param("keywordId")Long keywordId,@Param("commodyId") Long commodyId);

	void clearKeywordAboutCommody(long commodyId);

	Keyword selectKeywordByKeywordContent(String content);

}