package bbs.shop.mybatis.mapper;

import bbs.shop.entity.SubClass;
import bbs.shop.mybatis.entity.TSubClass;
import bbs.shop.mybatis.entity.TSubClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSubClassMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	long countByExample(TSubClassExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByExample(TSubClassExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insert(TSubClass record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insertSelective(TSubClass record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	List<TSubClass> selectByExample(TSubClassExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	TSubClass selectByPrimaryKey(Integer id);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TSubClass record, @Param("example") TSubClassExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExample(@Param("record") TSubClass record, @Param("example") TSubClassExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKeySelective(TSubClass record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_subclass
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKey(TSubClass record);


	void associateSubClassToCommody(@Param("subClassId") Integer subClassId,@Param("commodyId") Long commodyId);

	
	void unassociateSubClassToCommody(@Param("subClassId") Integer subClassId,@Param("commodyId") Long commodyId);


	SubClass selectSubClassById(int subClassId);  
}