package bbs.shop.mybatis.mapper;

import bbs.shop.entity.UserPerference;
import bbs.shop.mybatis.entity.TUserPerference;
import bbs.shop.mybatis.entity.TUserPerferenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import bbs.shop.mybatis.entity.TUserPerferenceKey;

public interface TUserPerferenceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	long countByExample(TUserPerferenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByExample(TUserPerferenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int deleteByPrimaryKey(TUserPerferenceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insert(TUserPerference record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int insertSelective(TUserPerference record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	List<TUserPerference> selectByExample(TUserPerferenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	TUserPerference selectByPrimaryKey(TUserPerferenceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TUserPerference record,
			@Param("example") TUserPerferenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByExample(@Param("record") TUserPerference record, @Param("example") TUserPerferenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKeySelective(TUserPerference record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_perference
	 * @mbg.generated  Sun Aug 05 20:14:06 CST 2018
	 */
	int updateByPrimaryKey(TUserPerference record);

	UserPerference selectUserPerferenceByUid(long uid);

	void updateFrequencyByUidAndKeywordContent(@Param("userId") long uid,@Param("keywordContent") String content);
}