package bbs.shop.mapper;

import bbs.shop.entity.TCommodyClassification;
import bbs.shop.entity.TCommodyClassificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCommodyClassificationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	long countByExample(TCommodyClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int deleteByExample(TCommodyClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int insert(TCommodyClassification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int insertSelective(TCommodyClassification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	List<TCommodyClassification> selectByExample(TCommodyClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	TCommodyClassification selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TCommodyClassification record,
			@Param("example") TCommodyClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int updateByExample(@Param("record") TCommodyClassification record,
			@Param("example") TCommodyClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int updateByPrimaryKeySelective(TCommodyClassification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_classification
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int updateByPrimaryKey(TCommodyClassification record);
}