package bbs.shop.mapper;

import bbs.shop.DTO.CommodyRecommend;
import bbs.shop.entity.TCommodyRecommend;
import bbs.shop.entity.TCommodyRecommendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCommodyRecommendMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	long countByExample(TCommodyRecommendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int deleteByExample(TCommodyRecommendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int insert(TCommodyRecommend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int insertSelective(TCommodyRecommend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	List<TCommodyRecommend> selectByExample(TCommodyRecommendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	TCommodyRecommend selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TCommodyRecommend record,
			@Param("example") TCommodyRecommendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int updateByExample(@Param("record") TCommodyRecommend record, @Param("example") TCommodyRecommendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int updateByPrimaryKeySelective(TCommodyRecommend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_commody_recommend
	 * @mbg.generated  Wed Jul 25 22:39:52 CST 2018
	 */
	int updateByPrimaryKey(TCommodyRecommend record);

	CommodyRecommend selectCommodyRecommendById(int recommendId);
}